prometheus:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  nodeSelector:
    yandex.cloud/node-group-id: catjfbbimoh5ondn7i35
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.51.250.12.209.nip.io
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  nodeSelector:
    yandex.cloud/node-group-id: catjfbbimoh5ondn7i35
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.51.250.12.209.nip.io
  adminPassword: admin
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-loki-distributed-query-frontend.observability:3100
